spring :
  application :
    name : CONFIG-SERVER3

  cloud :
    config :
      server :
        git :
          uri : https://github.com/PoojaWagh0410/ECommerce-ms-configServer
          clone-on-start : true


server :
  port : 8084